[package]
name = "neural_network"
version = "0.1.1"
edition = "2018"

[dependencies]
plotters = {version = "0.3.1", features = ["svg_backend"] }
rand = "0.8.4"
rand_distr = "0.4.2"

[dev-dependencies]
byteorder = "1.3"